name: Common Config

on:
  workflow_call:
  # Map the workflow outputs to job outputs
    outputs:
      repo-list:
        description: "The repo list"
        value: ${{ jobs.prepare.outputs.repo-list }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      repo-list: ${{ steps.set-repo-list.outputs.repo-list }}
    steps:
      - name: Set repository list
        id: set-repo-list
        run: |
          echo '["action1", "action2"]' > json_output.txt
          echo "repo-list=$(cat json_output.txt)" >> $GITHUB_OUTPUT
