name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Release branch name (e.g., release/v1.0.0)'
        required: true
        type: string

jobs:
  create_release_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run create_release_branch script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          #!/bin/bash

          echo "GH_PATH"
          echo $GH_PAT

          # 仓库列表
          repos=("action1" "action2") # 替换为你的仓库名称

          # Release 分支名称
          release_branch="${{ github.event.inputs.release_branch }}"

          for repo in "${repos[@]}"; do
            echo "Processing $repo..."

            # 克隆仓库
            git clone https://$GH_PAT@github.com/MeerkatKing/$repo.git
            cd $repo

            # 切换到 main 分支并拉取最新更改
            git checkout main
            git pull origin main

            # 创建 release 分支
            git checkout -b $release_branch

            # 推送到远程
            git push origin $release_branch

            # 返回管理仓库目录
            cd ..

            # 删除本地克隆
            rm -rf $repo

            echo "$repo release branch '$release_branch' created."
          done
