# 管理仓库中的工作流 .github/workflows/manage_release.yml
name: Manage Releases

on:
  workflow_dispatch:  # 手动触发

jobs:
  trigger_sub_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Release in Sub-Repositories
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/MeerkatKing/action2/actions/workflows/on-pr.yml/dispatches
          mediaType: '{"format": "json"}'
          request: '{"ref": "main", "inputs": {"tag_name": "v1.0.2", "release_notes": "统一管理的发布版本"}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
