name: Common Config

on:
  workflow_call:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      repo-list: “haha"
    steps:
      - name: Set repository list
        id: set-repo-list
        run: |
          echo '["action1", "action2"]' > json_output.txt
          echo "repo-list=$(cat json_output.txt)" >> $GITHUB_OUTPUT
