name: Common Config

on:
  workflow_call:

env:
  REPOS: '\"[\"action1\", \"action2\"]\"'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      repo-list: ${{ steps.set-repo-list.outputs.repo-list }}
    steps:
      - name: Set repository list
        id: set-repo-list
        run: |
          echo "repo-list=${{env.REPOS}}" >> "${{GITHUB_OUTPUT}}"
